from ESIServer.component.elasticsearch.search import search_articles
from ESIServer.component.open_relation_extraction.extract import extract
from ESIServer.component.word_link.WordGraph import WordGraph